version: "3.9"
services:
  redis:
    image: "redis:alpine"
  backend:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  frontend:
    build: ./front
    ports:
      - "5173:5173"
    depends_on:
      - backend


